language: objective-c
osx_image: xcode7.1
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - ./scripts/unstash.sh
script:
  - ./scripts/test.sh | xcpretty -c -f `xcpretty-travis-formatter`
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
